### ISSUE TITLE
Does this repro accept pull request?

### ISSUE THREAD

**Issue by ymc9** [rw3iss/esbuild-envfile-plugin#10]
If so, I'd like to submit one to fix the infinite recursion issue walking up the directories.

Thanks!

**Comment by rw3iss** [comment]
Yeah sure. Thanks 👍

**Comment by ymc9** [comment]
Cool! Do you mind adding me as a contributor? I've got a PR ready.

**Comment by ymc9** [comment]
Cool! I've got it ready here: #11 
Please check if it makes sense to you. Thanks!

**Comment by rw3iss** [comment]
Thanks to @ymc9 for the work and PR fix for this issue! 🎉
It is integrated, and version bumped to v1.0.4.
Please update and let me know if any issues remain.
Thanks again.
