### ISSUE TITLE
Empty .env file required for this plugin to work

### ISSUE THREAD

**Issue by rsdsllc-com-dipenc** [rw3iss/esbuild-envfile-plugin#13]
I am working on a rails app with esbuild. I am getting an error if I don't have an empty .env file even though I set the required environment variable using "export" command in terminal. 

Some of the packages in my package.json file:

```json
{
    "dotenv": "^16.4.5",
    "esbuild": "^0.20.2",
    "esbuild-envfile-plugin": "^1.0.5",
    "esbuild-rails": "^1.0.7",
}
```

Part of my esbuild.config.mjs:
```js
const config = {
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  bundle: true,
  entryPoints: entryPoints,
  minify: process.env.RAILS_ENV == "production",
  outdir: path.join(process.cwd(), "app/assets/builds"),
  plugins: [rails(), envFilePlugin],
  loader: {
    ".png": "file",
  },
  publicPath: "/assets",
  assetNames: "[name]-[hash].digested",
};
```

My javascript has something like this:
```js
import { WELCOME_MSG } from "env";
```

In terminal I am setting the environment variable:
```sh
export WELCOME_MSG=Hello
```

When I run my rails app, I get the error:
`[ERROR] No matching export in "env-ns:env" for import "WELCOME_MSG"`

Now if I add an empty .env file with `touch .env`, there are no errors. I shouldn't need to have an empty .env file for this to work.

**Comment by rsdsllc-com-dipenc** [comment]
The reason I want this plugin to work without requiring a .env file is because in development environment I use .env file but in production environment, I don't use .env file and I use environment variables instead.

**Comment by rw3iss** [comment]
Resolved with https://github.com/rw3iss/esbuild-envfile-plugin/pull/14 and other latest coming commits.
