### ISSUE TITLE
utils.js: fs is not defined

### ISSUE THREAD

**Issue by overdrivemachines** [rw3iss/esbuild-envfile-plugin#15]
In the most recent release, you moved the function findEnvFile to the file utils.js. In that file you need to declare `path` and `fs` before using them like this:

```js
const path = require("path");
const fs = require("fs");
const findEnvFile = (dir, rootPath, env) => {
}
```

By not declaring them, I am getting the error:

![image](https://github.com/rw3iss/esbuild-envfile-plugin/assets/1007217/93e78f9e-6b93-4186-a287-9ba375ac4c89)

**Comment by danwish24** [comment]
I'm having the same issue.  Looking forward to the PR being merged!

**Comment by rw3iss** [comment]
Thanks guys, sorry I missed that. Lmk if any other issues.

**Comment by danwish24** [comment]
Ryan, I'm seeing that you merged the PR but when I use npm to get the most recent version, it is still pulling the old version.  Has the updated version been published?

**Comment by rw3iss** [comment]
My mistake, sorry am doing too much. It's published now, thanks.
