### ISSUE TITLE
Could not resolve "env"

### ISSUE THREAD

**Issue by markskayff** [rw3iss/esbuild-envfile-plugin#9]
Seems the module name is not being resolved for some reason. 
I have .env file present in root.
`
✘ [ERROR] Could not resolve "env"

    src/redux/constants.js:1:21:
      1 │ import * as env from 'env';
`
Using node v16.17.1.
Managing dependencies with yarn 3.2.4

**Comment by rastro-dev** [comment]
File - node_modules/esbuild-envfile-plugin/index.js

Line 16 should be back to normal -> : _findEnvFile(path.resolve(dir, "../"));

**Comment by rw3iss** [comment]
@rastro-dev @markskayff Committed the change back. 
I haven't tested this stuff (ie. prod environment usage). Please let me know if it breaks, or anyone else. Will close for now.

If it happens to break again, we'll leave undefined and I'll revisit this whole plugin in a little while, or someone else can suggest a better PR. 

Thanks guys👍
